package common;

public enum ErrorCode {
    NONE,
    NO_CHAT_CREATED,
    NO_MATCHING_CHAT,
    PARTICIPANT_ALREADY_ADDED,
    INTERNAL_ERROR,
    CAN_NOT_REMOVE_ITSELF,
    PARTICIPANT_NOT_EXIST_IN_CHAT,
    ONLY_ADMIN_CAN_REMOVE_PARTICIPANT
}
